services:
  - type: web
    name: trading-dashboard
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "cd backend && python stock_service.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
    numInstances: 1
